//===-- EpiphanySchedule.td - Epiphany Scheduling Defs -----*- tablegen -*-===//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//

def GenericItineraries : ProcessorItineraries<[], [], []>;
